# Check the documentation at https://goreleaser.com
version: 2

builds:
  - id: octl
    binary: octl
    main: .
    ldflags:
      - -s -w
      - -X github.com/stellwerk-labs/platform-orchestrator-cli/internal.ModuleVersion={{ .Version }}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v1
      - linux_arm64
      - windows_amd64_v1
      - darwin_amd64_v1
      - darwin_arm64

archives:
  - format_overrides:
      - goos: windows
        formats: ['zip']
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - '--oidc-provider=github-actions'
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes
    artifacts: all
    output: true

homebrew_casks:
  - name: octl
    homepage: "https://docs.stellwerk.dev"
    description: "The CLI for Stellwerk, octl."
    license: EUPL-1.2
    binaries:
      - octl
    repository:
      owner: stellwerk-labs
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GH_PAT }}"
    commit_author:
      name: stellwerk-labs
      email: hello@stellwerk.dev

scoops:
  - name: octl
    homepage: "https://docs.stellwerk.dev"
    description: "The CLI for Stellwerk, octl."
    repository:
      owner: stellwerk-labs
      name: scoop-bucket
      branch: main
      token: "{{ .Env.GH_PAT }}"
    commit_author:
      name: stellwerk-labs
      email: hello@stellwerk.dev

dockers_v2:
  - id: octl
    ids:
      - octl
    dockerfile: goreleaser.Dockerfile
    images:
      - ghcr.io/stellwerk-labs/octl
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
      - latest
    labels:
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .CommitDate }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - "--pull"
